### ISSUE TITLE
Discover page: "sort by" is not working

### ISSUE THREAD

**Issue by vkoukos** [alexandrosraikos/policyms#106]
![image](https://user-images.githubusercontent.com/90182603/146017341-b7e26bce-69e9-48dc-90ff-3e4afc4487ec.png)

**Comment by alexandrosraikos** [comment]
Fixed on my end, but @vkoukos sorting is not working when other filters are present.

API call: `/descriptions/all?sortBy=views-asc&page=1&itemsPerPage=10&metadata.provider=vkoukos`
Result:
![Στιγμιότυπο 2021-12-15, 12 33 04 μμ](https://user-images.githubusercontent.com/32958223/146170652-9554c027-9325-49a3-9ba5-54af524602f7.png)
